### ISSUE TITLE
Samples not parsed

### ISSUE THREAD

**Issue by nbareil** [Te-k/cobaltstrike#3]
The following samples cannot be parsed by your script (while [SentinelOne](https://github.com/Sentinel-One/CobaltStrikeParser)'s one works) :

1538339863779e04fa6578bd24fdba8e397d0563ac1776e0e941ebf17a15cec6 42a96ff5ba5f5f7e07f296237d9dc04db1f4de200e5d5106b140d36c6e06fc10 6ffacc3363ffa170b1c06a3f0f9612d968397ebcbf754e54431f0ea6d45ee124 ac6f07d03eb84a5ffa3149766e1746a4645faf89b376540af2919c914592ee7e

Files attached (password: infected)
[m.zip](https://github.com/Te-k/cobaltstrike/files/5815997/m.zip)

**Comment by Te-k** [comment]
3 of these samples have a configuration in clear text and not xored, not sure why but b5fb9c8919ce5e59b4d0f0b962a72e759295bd0c adds support for it : 

```
$ python ../github/analyze.py  1538339863779e04fa6578bd24fdba8e397d0563ac1776e0e941ebf17a15cec6
Unknown config command 48
dns                            False
ssl                            True
port                           443
.sleeptime                     9300
.http-get.server.output        
.jitter                        15
.maxdns                        244
publickey                      30819f300d06092a864886f70d010101050003818d003081890281810091f28b9c4f213d42a1ba5aca5870a080c58f41563a190273c957dca8f63e4bdad04b931caef73357a81d8fbbd4a054a6503d5bbce0d1599546050d2a6cba001cd5990cf8a05cb559f7067b09d5776be5c653516087f5b60577c9731014bc8cf5a0bdb9c19158455dfc84ad8f5d1232d55a511e613f1f1abaacbea9661b83c603020301000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
.http-get.uri                  node.podzone.org,/safebrowsing/rd/mODJ1ES0Wz7G1LVVRyywNg4L5QVZny5yJ-5jGntzPtRUD
.user-agent                    Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36
.http-post.uri                 /safebrowsing/rd/BVVleixqc2yE9XEvpzil9yefZaygJpsth
.http-get.client               
GAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflaPREF=ID=Cookie
.http-post.client              
GAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflatU=Cekla82O8iJoVojPREF=ID=Cookie
.post-ex.spawnto_x86           %windir%\syswow64\rundll32.exe
.post-ex.spawnto_x64           %windir%\sysnative\rundll32.exe
.pipename                      
.cryptoscheme                  1
.dns_idle                      0
.dns_sleep                     0
.http-get.verb                 GET
.http-post.verb                POST
shouldChunkPosts               0
.watermark                     0
.stage.cleanup                 0
CFGCaution                     0
.proxy_type                    2
killdate                       0
text_section                   0
process-inject-start-rwx       64
process-inject-use-rwx         64
process-inject-min_alloc       0
process-inject-transform-x86   
process-inject-transform-x64   
48                             7
```
(Which is an APT32 related sample from 2017 if I am right)

The last file 42a96ff5ba5f5f7e07f296237d9dc04db1f4de200e5d5106b140d36c6e06fc10 is likely corrupted, but I am not sure why and how : strings like `%d.%s.post.cdn.%x%x.%s.www6.%x%x` are `%d)%s.post.cdn)%x%x)%s.www6)%x%x` in this sample, like if some dots were replaced by `)`, but not all of them. It is the case also for the configuration and it may also explain the invalid PE format. So I am tempted to consider it corrupted until I find another sample with the same issue, unless you specifically need to extract this configuration (in that case, xoring everything with 0x2e should give you some weird corrupted conf).

Thanks for sharing !

**Comment by Te-k** [comment]
Closing this ticket now, but feel free to reopen it if you have more unparsed samples
